export const userActions = {
  USER_SIGN_UP_INITIATE: "USER_SIGN_UP_INITIATE",
  USER_SIGN_UP_SUCCESS: "USER_SIGN_UP_SUCCESS",
  USER_SIGN_UP_FAILURE: "USER_SIGN_UP_FAILURE",
  USER_LOGIN_INITIATE: "USER_LOGIN_INITIATE",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  CLEAR_USER_SIGN_UP: "CLEAR_USER_SIGN_UP",
  CLEAR_USER_LOGIN_DATA: "CLEAR_USER_LOGIN_DATA",
};