export const userActions = {
  USER_SIGN_UP_INITIATE: "USER_SIGN_UP_INITIATE",
  USER_SIGN_UP_SUCCESS: "USER_SIGN_UP_SUCCESS",
  USER_SIGN_UP_FAILURE: "USER_SIGN_UP_FAILURE",
  USER_LOGIN_INITIATE: "USER_LOGIN_INITIATE",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  CLEAR_USER_SIGN_UP: "CLEAR_USER_SIGN_UP",
  CLEAR_USER_LOGIN_DATA: "CLEAR_USER_LOGIN_DATA",
  FORGOT_PASSWORD_INITIATE: "FORGOT_PASSWORD_INITIATE",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
  CHANGE_PASSWORD_INITIATE: "CHANGE_PASSWORD_INITIATE",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
};

export const postActions = {
  CREATE_NEW_POST_INITIATE: "CREATE_NEW_POST_INITIATE",
  CREATE_NEW_POST_SUCCESS: "CREATE_NEW_POST_SUCCESS",
  CREATE_NEW_POST_FAILURE: "CREATE_NEW_POST_FAILURE",
  CLEAR_POST_DATA:'CLEAR_POST_DATA'
};
